"""Run all 10 public sample cases through the full pipeline and print a table.

Usage:
    python -m scripts.evaluate
    python -m scripts.evaluate --cases data/raw/sample_cases.json
    python -m scripts.evaluate --use-llm   # (Phase B only)

For each case this prints:
    Case ID    | Directive Match | Constraints | Cost | Ref Cost | Δ
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from llm.schema import InputSchema, OutputSchema
from optimizer.model import InfeasibleScheduleError, optimize_schedule
from optimizer.rules_fallback import parse_notes
from optimizer.validate import directive_matches, validate_output


def load_sample_cases(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    return data["cases"]


def run_case(case: dict[str, Any], use_llm: bool = False) -> dict[str, Any]:
    """Run a single case. Returns a dict of metrics."""
    inp = InputSchema.model_validate(case["input"])
    expected = OutputSchema.model_validate(case["expected_output"])

    if use_llm:
        from llm.inference import parse_directives_with_llm
        try:
            directives = parse_directives_with_llm(inp)
        except Exception as e:
            print(f"  [warn] LLM failed: {e}; falling back to rules")
            directives = parse_notes(inp)
    else:
        directives = parse_notes(inp)

    try:
        actual = optimize_schedule(
            inp,
            directives,
            plan_summary="Generated by GridWise Phase A (rules + LP).",
        )
    except InfeasibleScheduleError as e:
        return {
            "case_id": case["id"],
            "label": case.get("label", ""),
            "directive_ok": False,
            "constraints_ok": False,
            "actual_cost": None,
            "ref_cost": expected.total_cost_bdt,
            "delta_cost": None,
            "error": f"Infeasible: {e}",
        }

    dir_ok, dir_msg = directive_matches(actual, expected)
    constraints_ok, _ = validate_output(inp, actual)
    actual_cost = actual.total_cost_bdt
    ref_cost = expected.total_cost_bdt
    delta = actual_cost - ref_cost

    return {
        "case_id": case["id"],
        "label": case.get("label", ""),
        "directive_ok": dir_ok,
        "constraints_ok": constraints_ok,
        "actual_cost": actual_cost,
        "ref_cost": ref_cost,
        "delta_cost": delta,
        "error": None if dir_ok else dir_msg,
    }


def print_table(rows: list[dict[str, Any]]) -> None:
    print()
    print(f"{'CASE':<12}{'DIRECTIVE':<12}{'CONSTRAINTS':<14}"
          f"{'COST':>12}{'REF':>12}{'DELTA':>10}  LABEL")
    print("-" * 90)
    for r in rows:
        d = "OK" if r["directive_ok"] else "FAIL"
        c = "OK" if r["constraints_ok"] else "FAIL"
        if r["actual_cost"] is None:
            cost_s = "  --"
            ref_s = f"{r['ref_cost']:>12.2f}" if r["ref_cost"] is not None else "  --"
            delta_s = "  --"
        else:
            cost_s = f"{r['actual_cost']:>12.2f}"
            ref_s = f"{r['ref_cost']:>12.2f}"
            delta_s = f"{r['delta_cost']:>+10.2f}"
        err = f"  [{r['error']}]" if r.get("error") else ""
        print(f"{r['case_id']:<12}{d:<12}{c:<14}"
              f"{cost_s}{ref_s}{delta_s}  {r['label']}{err}")
    print()

    n = len(rows)
    n_dir = sum(1 for r in rows if r["directive_ok"])
    n_con = sum(1 for r in rows if r["constraints_ok"])
    n_cost_match = sum(
        1 for r in rows
        if r["actual_cost"] is not None
        and abs(r["delta_cost"]) <= 0.01
    )
    print(f"Summary: {n_dir}/{n} directives matched, "
          f"{n_con}/{n} constraint-satisfying, "
          f"{n_cost_match}/{n} exact-cost matches.")
    print()


def main() -> None:
    parser = argparse.ArgumentParser(description="Run all 10 sample cases.")
    parser.add_argument("--cases", type=str, default="data/raw/sample_cases.json")
    parser.add_argument("--use-llm", action="store_true",
                        help="Use the fine-tuned LLM instead of the rule parser (Phase B).")
    args = parser.parse_args()

    here = Path(__file__).resolve().parent.parent
    cases_path = here / args.cases
    cases = load_sample_cases(cases_path)
    print(f"Loaded {len(cases)} cases from {cases_path}")

    rows = [run_case(c, use_llm=args.use_llm) for c in cases]
    print_table(rows)


if __name__ == "__main__":
    main()
